### ISSUE TITLE
Customer is unable to access content 

### ISSUE THREAD

**Issue by omehes** [openstax/webview#2281]
user can't view his personal workspace, the collection is col30267, Introduction to the Human Body fvcc104. The content team was not able to replicate his error. 

Here is the link to his workspace: https://legacy.cnx.org/Members/ctaylor_fvcc 

When going to this link, I am seeing 500 error (see attached)

More details from the customer and Tabitha H.
Hello! This guy came back. He's continuing to experience problems when logging into cnx. He included several screenshots. He had a few comments and questions. When I click on personal workspace I get the error above.
If I click on Modules I can access the modules only (which is something.) I have a suspicion that the last module "Divisions of the Autonomic Nervous System" may be causing problems because if I try to open the module I get this error: If I try to delete that module I get this error: I am feeling a little nervous as I am doing a lot of editing!
I am feeling a little nervous as I am doing a lot of editing!
Is it possible for you to delete that last module from your end?

Otto: I submitted the case to devops team to see what is causing the 500 error when accessing the site. Still under investigation

Screenshots from customer:

![image__3__160.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/2d267588-b7f9-4a99-9e38-1f64a81530f1)

![image__2__160.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/d0b70bbd-319a-46e1-999c-1deeaae12358)

![image__1__160.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/6b25cd0b-1caf-4bcc-aace-fae737aa513d)

![image_160.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/2668caa8-f160-4f64-b597-5ddfe9feea0b)

500 error:

![customer-1_160.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/b35fb17f-bdcf-43f0-8f40-656c319ecc53)

**Comment by omehes** [comment]
Notes from devops:

These are potential candidates from /var/lib/cnx/cnx-buildout/var/log/instance0.log on prod04

<details>
<summary>Click here for more info</summary>

  Module Products.PageTemplates.TALES, line 221, in evaluate
   - URL: file:RhaptosRepository/skins/rhaptos_repository/expanded_browse_authors.cpt
   - Line 177, Column 20
   - Expression: standard:'context/expanded_browse_authors_view'
   - Names:
      {'container': <PloneSite at /plone>,
       'context': <Repository at /plone/content>,
       'default': <Products.PageTemplates.TALES.Default instance at 0x7f486d3d5cf8>,
       'here': <Repository at /plone/content>,
       'loop': <Products.PageTemplates.TALES.SafeMapping object at 0x7f485f38b830>,
       'modules': <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter instance at 0x7f486d3d8488>,
       'nothing': None,
       'options': {'args': (),
                   'state': <Products.CMFFormController.ControllerState.ControllerState object at 0x7f48423bec50>},
       'repeat': <Products.PageTemplates.TALES.SafeMapping object at 0x7f485f38b830>,
       'request': <HTTPRequest, URL=https://legacy.cnx.org/content/expanded_browse_authors>,
       'root': <Application at >,
       'template': <FSControllerPageTemplate at /plone/expanded_browse_authors used for /plone/content>,
       'traverse_subpath': [],
       'user': <SpecialUser 'Anonymous User'>}
  Module Products.PageTemplates.Expressions, line 185, in __call__
  Module Products.PageTemplates.Expressions, line 180, in _eval
  Module Products.PageTemplates.Expressions, line 77, in render
  Module Products.PageTemplates.ZRPythonExpr, line 78, in call_with_ns
  Module Products.CMFCore.FSPythonScript, line 103, in __render_with_namespace__
  Module Shared.DC.Scripts.Bindings, line 325, in __render_with_namespace__
  Module Products.PloneHotfix20110531, line 106, in _patched_bindAndExec
  Module Products.PloneHotfix20130618.spamProtect, line 35, in _patched_bindAndExec
  Module Products.PloneHotfix20121106.python_scripts, line 63, in _patched_bindAndExec
  Module Shared.DC.Scripts.Bindings, line 348, in _bindAndExec
  Module Products.CMFCore.FSPythonScript, line 164, in _exec
  Module None, line 25, in expanded_browse_authors_view
   - <FSPythonScript at /plone/expanded_browse_authors_view used for /plone/content>
   - Line 25
AttributeError: 'NoneType' object has no attribute 'surname'
and
2019-10-09T22:30:10 ERROR root Exception while rendering an error message
Traceback (most recent call last):
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/OFS/SimpleItem.py", line 223, in raise_standardErrorMessage
    v = s(**kwargs)
  File "/var/lib/cnx/cnx-buildout/parts/plone/CMFCore/FSPythonScript.py", line 108, in __call__
    return Script.__call__(self, *args, **kw)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Shared/DC/Scripts/Bindings.py", line 311, in __call__
    return self._bindAndExec(args, kw, None)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.PloneHotfix20110531-2.0-py2.4.egg/Products/PloneHotfix20110531/__init__.py", line 106, in _patched_bindAndExec
    return self._original_bindAndExec(args, kw, caller_namespace)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.PloneHotfix20130618-1.1-py2.4.egg/Products/PloneHotfix20130618/spamProtect.py", line 35, in _patched_bindAndExec
    return _original_bindAndExec(self, args, kw, caller_namespace)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.PloneHotfix20121106-1.2-py2.4.egg/Products/PloneHotfix20121106/python_scripts.py", line 63, in _patched_bindAndExec
    return _original_bindAndExec(self, args, kw, caller_namespace)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Shared/DC/Scripts/Bindings.py", line 348, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/var/lib/cnx/cnx-buildout/parts/plone/CMFCore/FSPythonScript.py", line 164, in _exec
    result = f(*args, **kw)
  File "Script (Python)", line 25, in standard_error_message
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Shared/DC/Scripts/Bindings.py", line 311, in __call__
    return self._bindAndExec(args, kw, None)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.PloneHotfix20110531-2.0-py2.4.egg/Products/PloneHotfix20110531/__init__.py", line 106, in _patched_bindAndExec
    return self._original_bindAndExec(args, kw, caller_namespace)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.PloneHotfix20130618-1.1-py2.4.egg/Products/PloneHotfix20130618/spamProtect.py", line 35, in _patched_bindAndExec
    return _original_bindAndExec(self, args, kw, caller_namespace)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.PloneHotfix20121106-1.2-py2.4.egg/Products/PloneHotfix20121106/python_scripts.py", line 63, in _patched_bindAndExec
    return _original_bindAndExec(self, args, kw, caller_namespace)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Shared/DC/Scripts/Bindings.py", line 348, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/var/lib/cnx/cnx-buildout/parts/plone/CMFCore/FSPageTemplate.py", line 195, in _exec
    result = self.pt_render(extra_context=bound_names)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.CacheSetup-1.2.1-py2.4.egg/Products/CacheSetup/patch_cmf.py", line 29, in FSPT_pt_render
    return call_pattern(self, 'pt_render', '__CacheSetup_FSPageTemplate_%s__', source, extra_context)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.CacheSetup-1.2.1-py2.4.egg/Products/CacheSetup/patch_utils.py", line 9, in call_pattern
    return getattr(self, pattern % __name__)(*args, **kw)
  File "/var/lib/cnx/cnx-buildout/parts/plone/CMFCore/FSPageTemplate.py", line 134, in pt_render
    result = FSPageTemplate.inheritedAttribute('pt_render')(
  File "/var/lib/cnx/cnx-buildout/eggs/Products.CacheSetup-1.2.1-py2.4.egg/Products/CacheSetup/patch_cmf.py", line 77, in PT_pt_render
    return call_pattern(self, 'pt_render', '__CacheSetup_PageTemplate_%s__', source, extra_context)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.CacheSetup-1.2.1-py2.4.egg/Products/CacheSetup/patch_utils.py", line 9, in call_pattern
    return getattr(self, pattern % __name__)(*args, **kw)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/PageTemplates/PageTemplate.py", line 104, in pt_render
    tal=not source, strictinsert=0)()
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/TAL/TALInterpreter.py", line 238, in __call__
    self.interpret(self.program)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/TAL/TALInterpreter.py", line 281, in interpret
    handlers[opcode](self, args)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/TAL/TALInterpreter.py", line 749, in do_useMacro
    self.interpret(macro)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/TAL/TALInterpreter.py", line 281, in interpret
    handlers[opcode](self, args)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/TAL/TALInterpreter.py", line 457, in do_optTag_tal
    self.do_optTag(stuff)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/TAL/TALInterpreter.py", line 442, in do_optTag
    return self.no_tag(start, program)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/TAL/TALInterpreter.py", line 437, in no_tag
    self.interpret(program)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/TAL/TALInterpreter.py", line 281, in interpret
    handlers[opcode](self, args)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/TAL/TALInterpreter.py", line 749, in do_useMacro
    self.interpret(macro)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/TAL/TALInterpreter.py", line 281, in interpret
    handlers[opcode](self, args)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/TAL/TALInterpreter.py", line 310, in do_startEndTag
    self.do_startTag(stuff, self.endsep, self.endlen)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/TAL/TALInterpreter.py", line 339, in do_startTag
    ok, name, s = attrAction(self, item)
  File "/var/lib/cnx/cnx-buildout/parts/plone/PlacelessTranslationService/PatchStringIO.py", line 158, in patched_attrAction_tal
    evalue = self.engine.evaluateText(item[3])
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/PageTemplates/TALES.py", line 227, in evaluateText
    text = self.evaluate(expr)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/PageTemplates/TALES.py", line 221, in evaluate
    return expression(self)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/PageTemplates/Expressions.py", line 224, in __call__
    v = var(econtext)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/PageTemplates/Expressions.py", line 185, in __call__
    return self._eval(econtext)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/PageTemplates/Expressions.py", line 173, in _eval
    ob = self._subexprs[-1](econtext)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/PageTemplates/Expressions.py", line 127, in _eval
    ob = restrictedTraverse(ob, path, getSecurityManager())
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/PageTemplates/Expressions.py", line 310, in restrictedTraverse
    raise Unauthorized, name
Unauthorized: You are not allowed to access 'Creator' in this context
Collapse

</details>

**Comment by karenc** [comment]
This might be one of the errors: (`/var/lib/cnx/cnx-buildout/var/log/instance2.log` from `prod04`)

```
2019-10-15T09:37:01 ERROR Zope.SiteErrorLog https://legacy.cnx.org/Members/ctaylor_fvcc/workspace_contents
Traceback (innermost last):
  Module ZPublisher.Publish, line 115, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 41, in call_object
  Module Shared.DC.Scripts.Bindings, line 311, in __call__
  Module Products.PloneHotfix20110531, line 106, in _patched_bindAndExec
  Module Products.PloneHotfix20130618.spamProtect, line 35, in _patched_bindAndExec
  Module Products.PloneHotfix20121106.python_scripts, line 63, in _patched_bindAndExec
  Module Shared.DC.Scripts.Bindings, line 348, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 195, in _exec
  Module Products.CacheSetup.patch_cmf, line 29, in FSPT_pt_render
  Module Products.CacheSetup.patch_utils, line 9, in call_pattern
  Module Products.CMFCore.FSPageTemplate, line 134, in pt_render
  Module Products.CacheSetup.patch_cmf, line 77, in PT_pt_render
  Module Products.CacheSetup.patch_utils, line 9, in call_pattern
  Module Products.PageTemplates.PageTemplate, line 104, in pt_render
   - <FSPageTemplate at /plone/workspace_contents used for /plone/Members/ctaylor_fvcc>
  Module TAL.TALInterpreter, line 238, in __call__
  Module TAL.TALInterpreter, line 281, in interpret
  Module TAL.TALInterpreter, line 749, in do_useMacro
  Module TAL.TALInterpreter, line 281, in interpret
  Module TAL.TALInterpreter, line 457, in do_optTag_tal
  Module TAL.TALInterpreter, line 442, in do_optTag
  Module TAL.TALInterpreter, line 437, in no_tag
  Module TAL.TALInterpreter, line 281, in interpret
...
  Module TAL.TALInterpreter, line 772, in do_defineSlot
  Module TAL.TALInterpreter, line 281, in interpret
  Module TAL.TALInterpreter, line 507, in do_setLocal_tal
  Module Products.PageTemplates.TALES, line 221, in evaluate
   - URL: file:RhaptosSite/skins/rhaptos_site/workspace_contents.pt
   - Line 282, Column 20
   - Expression: standard:'item/getObject | nothing'
   - Names:
      {'container': <PloneSite at /plone>,
       'context': <PloneFolder at /plone/Members/ctaylor_fvcc>,
       'default': <Products.PageTemplates.TALES.Default instance at 0x7f4c53d34cf8>,
       'here': <PloneFolder at /plone/Members/ctaylor_fvcc>,
       'loop': <Products.PageTemplates.TALES.SafeMapping object at 0x7f4c1e177878>,
       'modules': <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter instance at 0x7f4c53d37488>,
       'nothing': None,
       'options': {'args': ()},
       'repeat': <Products.PageTemplates.TALES.SafeMapping object at 0x7f4c1e177878>,
       'request': <HTTPRequest, URL=https://legacy.cnx.org/Members/ctaylor_fvcc/workspace_contents>,
       'root': <Application at >,
       'template': <FSPageTemplate at /plone/workspace_contents used for /plone/Members/ctaylor_fvcc>,
       'traverse_subpath': [],
       'user': <PloneUser 'zumi'>}
  Module Products.PageTemplates.Expressions, line 185, in __call__
  Module Products.PageTemplates.Expressions, line 180, in _eval
  Module Products.PageTemplates.Expressions, line 85, in render
  Module Products.ZCatalog.CatalogBrains, line 86, in getObject
  Module OFS.Traversable, line 250, in restrictedTraverse
  Module OFS.Traversable, line 187, in unrestrictedTraverse
   - __traceback_info__: ([], '2019-10-03.2668647119')
  Module Products.Five.traversable, line 126, in __bobo_traverse__
AttributeError: 2019-10-03.2668647119
```

**Comment by pumazi** [comment]
The users content items: `['col30271', 'col30267', 'm79460', 'm79299', 'm79523', 'm79390', 'm79245', 'm79447', 'm79302', 'm79475', 'm79246', 'm79301', 'm79395', 'm79429', 'm79242', 'm79340', 'm79344', 'm79436', 'm79425', 'm79468', 'm79421', 'm79441', 'm79483', 'm79479', 'm79433', 'm79412', 'm79506', 'm79304', 'm79415', 'm79411', 'm79463', 'm79408', 'm79300', 'm79244', 'm79524', 'm79335', 'm79517', 'm79511', 'm79419', 'm79247', 'm79423', 'm79495', 'm79528', 'm79502', 'm79396', 'm79453', 'm79418', 'm79399', 'm79392', 'm79525', 'm79398', 'm79488', 'm79397', 'm79535', 'm79303', 'm79457', 'm79532', 'm79401', 'm79507', 'm79343', 'm79404', 'm79526']`

**Comment by karenc** [comment]
Objects in the user's workspace:

```
>>> app.plone.Members.ctaylor_fvcc.objectIds()
['Collection.2019-09-15.3234', 'm79344', 'm79242', 'm79244', 'm79335', 'm79340', 'm79304', 
'm79343', 'm79390', 'm79395', 'm79398', 'm79412', 'm79415', 'm79418', 'm79419', 'm79411', 
'm79423', 'm79408', 'm79421', 'm79441', 'm79447', 'm79425', 'm79429', 'm79433', 'm79460', 
'm79506', 'm79517', 'm79523', 'm79396', 'm79401', 'm79463', 'col30271', 'm79453', 'col30267', 
'm79457', 'm79488', 'm79507', 'm79475', 'm79511', 'Module.2019-10-02.3736', 'm79524', 
'm79525', 'm79399', 'm79404', 'm79436', 'm79392', 'm79397', 'm79479', 'm79483', 'm79502', 
'm79468', 'm79526', 'm79495', 'collection.2019-10-12.9578633123', 
'collection.2019-10-12.1114185423', 'collection.2019-10-12.2949128156', 
'collection.2019-10-12.4373991117', 'collection.2019-10-12.5237622138', 
'collection.2019-10-12.6984373249', 'collection.2019-10-12.7999829143', 'm79528', 'm79535', 
'm79532', 'Module.2019-10-12.4528', 'Module.2019-10-12.4601', 'Module.2019-10-12.5332', 
'Module.2019-10-12.5402', 'Module.2019-10-12.5413', 'Module.2019-10-12.5524', 
'Module.2019-10-12.5945', 'Module.2019-10-12.0002', 'Module.2019-10-12.0102', 
'Module.2019-10-12.0242', 'Module.2019-10-12.0257']
```

Workspace items returned by the portal catalog (used by the view):

```
>>> [i.getId for i in app.plone.portal_catalog.unrestrictedSearchResults({'path': {'query': '/plone/Members/ctaylor_fvcc', 'depth': 1}}, show_all=1)]
['m79453', 'm79483', 'm79495', 'm79511', 'm79399', 'm79401', 'm79418', 'm79441', 'm79524', 
'm79525', 'collection.2019-10-12.4373991117', 'm79475', 'collection.2019-10-12.1114185423', 
'collection.2019-10-12.6984373249', 'm79404', 'm79421', 'm79429', 'm79457', 
'Module.2019-10-12.4528', 'Module.2019-10-12.5332', 'Module.2019-10-12.0242', 'm79532', 
'2019-10-03.2668647119', 'Module.2019-10-12.0257', 'm79244', 
'collection.2019-10-12.7999829143', 'm79411', 'm79412', 'm79423', 'm79425', 'm79436', 'm79447', 
'm79390', 'm79517', 'Module.2019-10-12.5413', 'm79397', 'collection.2019-10-12.5237622138', 
'm79415', 'm79433', 'm79479', 'Module.2019-10-12.5945', 'Module.2019-10-12.0002', 
'Module.2019-10-12.0102', 'm79502', 'm79523', 'm79535', 'col30267', 'm79340', 
'Module.2019-10-02.3736', 'm79343', 'm79242', 'm79396', 'collection.2019-10-12.2949128156', 
'm79398', 'm79408', 'm79419', 'm79460', 'm79468', 'm79526', 'Module.2019-10-12.5524', 
'm79528', 'm79304', 'm79335', 'm79507', 'm79344', 'm79395', 'collection.2019-10-12.9578633123', 
'm79463', 'm79488', 'm79506', 'm79392', 'Module.2019-10-12.4601', 'col30271', 
'Collection.2019-09-15.3234', 'Module.2019-10-12.5402']
```

The difference:

```
>>> [i.getId for i in app.plone.portal_catalog.unrestrictedSearchResults({'path': {'query': '/plone/Members/ctaylor_fvcc', 'depth': 1}}, show_all=1) if i.getId not in app.plone.Members.ctaylor_fvcc.objectIds()]
['2019-10-03.2668647119']
```

**Comment by karenc** [comment]
What we need to do is to unindex the missing object from the portal catalog, otherwise the workspace can't display correctly.

This is the `unindexObject` code from /var/lib/cnx/cnx-buildout/parts/plone/CMFCore/CatalogTool.py:

```python
    security.declarePrivate('unindexObject')
    def unindexObject(self, object):
        '''Remove from catalog.
        '''
        url = self.__url(object)
        self.uncatalog_object(url)

    def __url(self, ob):
        return '/'.join( ob.getPhysicalPath() )

```

But trying to uncatalog the object raised an error:

```
>>> app.plone.portal_catalog.uncatalog_object('/plone/Members/ctaylor_fvcc/2019-10-03.2668647119')
Traceback (most recent call last):
  File "<stdin>", line 1, in ?                                                                                                                                                
  File "/var/lib/cnx/cnx-buildout/eggs/Products.CacheSetup-1.2.1-py2.4.egg/Products/CacheSetup/patch.py", line 109, in uncatalog_object
    return call(self, 'uncatalog_object', uid)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.CacheSetup-1.2.1-py2.4.egg/Products/CacheSetup/patch_utils.py", line 6, in call
    return getattr(self, PATTERN % __name__)(*args, **kw)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/ZCatalog/ZCatalog.py", line 599, in uncatalog_object
    self._catalog.uncatalogObject(uid)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/ZCatalog/Catalog.py", line 389, in uncatalogObject
    x.unindex_object(rid)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/PluginIndexes/DateRangeIndex/DateRangeIndex.py", line 192, in unindex_object
    self._removeForwardIndexEntry( since, until, documentId )
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/PluginIndexes/DateRangeIndex/DateRangeIndex.py", line 384, in _removeForwardIndexEntry
    set.remove( documentId )
KeyError: -990412476
```

I'll need to look into this tomorrow.

**Comment by karenc** [comment]
This looks similar to https://github.com/openstax/cnx/issues/561

**Comment by karenc** [comment]
Here's what I did in `/var/lib/cnx/cnx-buildout/bin/instance debug` on `prod04` to fix the problem:

```
>>> [i.getPath() for i in app.plone.portal_catalog.unrestrictedSearchResults({'path': {'query': '/plone/Members/ctaylor_fvcc', 'depth': 1}}, show_all=1) if i.getId not in app.plone.Members.ctaylor_fvcc.objectIds()]
['/plone/Members/ctaylor_fvcc/2019-10-03.2668647119']
>>> app.plone.portal_catalog.uncatalog_object('/plone/Members/ctaylor_fvcc/2019-10-03.2668647119')
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
  File "/var/lib/cnx/cnx-buildout/eggs/Products.CacheSetup-1.2.1-py2.4.egg/Products/CacheSetup/patch.py", line 109, in uncatalog_object
    return call(self, 'uncatalog_object', uid)
  File "/var/lib/cnx/cnx-buildout/eggs/Products.CacheSetup-1.2.1-py2.4.egg/Products/CacheSetup/patch_utils.py", line 6, in call
    return getattr(self, PATTERN % __name__)(*args, **kw)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/ZCatalog/ZCatalog.py", line 599, in uncatalog_object
    self._catalog.uncatalogObject(uid)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/ZCatalog/Catalog.py", line 389, in uncatalogObject
    x.unindex_object(rid)
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/PluginIndexes/DateRangeIndex/DateRangeIndex.py", line 192, in unindex_object
    self._removeForwardIndexEntry( since, until, documentId )
  File "/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/Products/PluginIndexes/DateRangeIndex/DateRangeIndex.py", line 384, in _removeForwardIndexEntry
    set.remove( documentId )
KeyError: -990412476

>>> er = app.plone.portal_catalog._catalog.getIndex('effectiveRange')

>>> rid = app.plone.portal_catalog._catalog.uids.get('/plone/Members/ctaylor_fvcc/2019-10-03.2668647119')

>>> since, until = er._unindex.get(rid)

>>> rid in er._since.get(since)
False
>>> rid in er._until.get(until)
True
>>> er._until.get(until).remove(rid)
>>> bool(er._until.get(until))
True
>>> del er._unindex[rid]
>>> app.plone.portal_catalog.uncatalog_object('/plone/Members/ctaylor_fvcc/2019-10-03.2668647119')
2019-10-16 09:10:36 ERROR Zope.UnIndex DateIndex: unindex_object tried to retrieve set 1081989948 from index Date but couldn't.  This should not happen.
>>> [i.getPath() for i in app.plone.portal_catalog.unrestrictedSearchResults({'path': {'query': '/plone/Members/ctaylor_fvcc', 'depth': 1}}, show_all=1) if i.getId not in app.plone.Members.ctaylor_fvcc.objectIds()]
[]
>>> import transaction
>>> transaction.commit()
```

@omehes Could you check to see if the user's workspace is working now?
